
- name: Install Prometheus (Ubuntu)
  apt:
    name: prometheus
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Enabling Prometheus Performance Tool
  service:
    name: prometheus
    state: restarted
    enabled: true
  when: ansible_distribution == "Ubuntu"

- name: Restaring Apache Service for Ubuntu
  service:
    name: prometheus
    state: restarted
    enabled: true
  when: ansible_distribution == "Ubuntu"
